### ISSUE TITLE
Can't record video stacks in camera module

### ISSUE THREAD

**Issue by campagnola** [acq4/acq4#155]
Clicking the "record stack" button in camera module results in the following:

```
Traceback (most recent call last):
  File "C:\Users\lukec\acq4\acq4\util\imaging\record_thread.py", line 133, in run
    self.handleFrames(newFrames)
  File "C:\Users\lukec\acq4\acq4\util\imaging\record_thread.py", line 191, in handleFrames
    self.writeFrames(recFrames, dh)
  File "C:\Users\lukec\acq4\acq4\util\imaging\record_thread.py", line 211, in writeFrames
    self.currentStack = dh.writeFile(data, 'video', autoIncrement=True, info=frames[0][1], appendAxis='Time', appendKeys=['translation'])
  File "C:\Users\lukec\acq4\acq4\util\DataManager.py", line 746, in writeFile
    fileName = fileClass.write(obj, self, fileName, **kwargs)
  File "C:\Users\lukec\acq4\acq4\filetypes\MetaArray.py", line 41, in write
    data.write(os.path.join(dirHandle.name(), fileName), **args)
  File "C:\Users\lukec\Miniconda3\envs\acq4\lib\site-packages\MetaArray\__init__.py", line 943, in write
    return self.writeMa(fileName, **opts)
TypeError: writeMa() got an unexpected keyword argument 'appendKeys'
```

**Comment by outofculture** [comment]
`appendKeys` is not supported by the old `.ma` format MetaArray files. `pip install h5py` to use the newer format.

**Comment by campagnola** [comment]
Turned out that the hdf5 package was broken, but this error was silently hidden. Better to require hdf5 by default and allow writing old-mode only by explicit request.

**Comment by outofculture** [comment]
Hmm. That would break existing code that depends on MetaArray, but I can start the deprecation cycle on MetaArray now. We can also just make the requirement explicit and early in ACQ4's startup. I'll do that, too.
