### ISSUE TITLE
ACQ4 fails to start

### ISSUE THREAD

**Issue by Taomach** [acq4/acq4#18]
Hello! I am trying to use ACQ4 under OpenSUSE 13.1 with python 2.7.6. Here is what I get:

```
user@patch:~/acq4> python -m acq4
Loading ACQ4...
===== 2015.04.19 20:04:57 =====
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/user/acq4/acq4/__main__.py", line 14, in <module>
    from .Manager import *
  File "acq4/Manager.py", line 25, in <module>
    from .util import DataManager, ptime, configfile
  File "acq4/util/DataManager.py", line 32, in <module>
    import acq4.filetypes as filetypes
  File "acq4/filetypes/__init__.py", line 1, in <module>
    from filetypes import *
  File "acq4/filetypes/filetypes.py", line 96, in <module>
    listFileTypes()
  File "acq4/filetypes/filetypes.py", line 92, in listFileTypes
    debug.printExc("Error loading file type library '%s':" % typ)
  File "acq4/util/debug.py", line 22, in printExc
    acq4.Manager.logExc(msg=msg, msgType=msgType)
AttributeError: 'module' object has no attribute 'Manager'
```

What am I doing wrong?

**Comment by campagnola** [comment]
Looks like one of the file type libraries is failing to load, but the error from that failure is being obscured by an unrelated bug in the error reporting system. Can you check that all dependencies installed correctly (especially h5py and PIL)?

If you try it again with the latest devleop branch on github, you should get a more useful error message.

**Comment by Taomach** [comment]
Thank you, the last revision works. The PIL library can't be found for some reason, but I think I'll solve in no time. Anyway, the program now works event without it.
