### ISSUE TITLE
track down access violation

### ISSUE THREAD

**Issue by outofculture** [acq4/acq4#229]

**Comment by outofculture** [comment]
```
acq4-torch) C:\Users\svc_multipatch\acq4>python -m acq4 -m MultiPatch
Loading ACQ4...
============= Starting Manager configuration from C:\Users\svc_multipatch\acq4\config\default.cfg =================
  === Configuring device 'DAQ' ===
Created NiDAQ handle, devices are ['Dev1', 'Dev2', 'Dev3']
  === Configuring device 'XKeys' ===
  === Configuring device 'LEDChannels' ===
  === Configuring device 'LEDs' ===
  === Configuring device 'Stage' ===
  === Configuring device 'SliceScope' ===
  === Configuring device 'Condenser' ===
  === Configuring device 'Microscope' ===
  === Configuring device 'MultiBand_FilterCube' ===
  === Configuring device 'EGFP_FilterCube' ===
  === Configuring device 'UV_FilterCube' ===
  === Configuring device 'FilterTurret' ===
  === Configuring device 'Camera' ===
ERROR:PyTic:TIC_ERROR_INTENTIONALLY_DEENERGIZED
ERROR:PyTic:TIC_ERROR_SAFE_START_VIOLATION
ERROR:PyTic:TIC_ERROR_INTENTIONALLY_DEENERGIZED
  === Configuring device 'Clamp2' ===
Created MultiClamp device model:MC700B,sn:00834228,chan:1
  === Configuring device 'Pressure1Channels' ===
  === Configuring device 'Pressure2Channels' ===
  === Configuring device 'Pressure1' ===
  === Configuring device 'Pressure2' ===
  === Configuring device 'Manipulator2' ===
  === Configuring device 'Pipette2' ===
  === Configuring device 'PatchPipette2' ===
  === Configuring device 'Photodiode' ===
  === Configuring device 'LaserFilter' ===
  === Configuring device 'Laser-Blue' ===
  === Configuring device 'Laser-Blue-raw' ===
  === Configuring device 'Scanner' ===
  === Configuring device 'Scanner-raw' ===
=== Device configuration complete ===
=== Setting default HDF5 compression: None ===
=== Setting base directory: D:\data ===
============= Manager configuration complete =================
Loading module "Manager" as "Manager"...
Loading module "MultiPatch" as "MultiPatch"...
Loaded module 'MultiPatch'
Loading module "DataManager" as "Data Manager"...
Loaded module 'Data Manager'
Loading module "Camera" as "Camera"...
Loaded module 'Camera'
CUDA enabled in config (cudaImageProcessing), but cupy could not be imported.
===== 2024.03.26 14:03:01 =====
Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Users\svc_multipatch\acq4\acq4\util\future.py", line 264, in _monitorErrors
    self.wait(pollInterval=pollInterval)
  File "C:\Users\svc_multipatch\acq4\acq4\util\future.py", line 190, in wait
    raise RuntimeError(msg)
RuntimeError: Task <acq4.devices.Stage.Stage.MovePathFuture object at 0x000001CA8AB58040> did not complete: Error in path move thread: Task <acq4.devices.Sensapex.SensapexMoveFuture object at 0x000001CA8ABCBB50> did not complete: stop requested before move finished
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\svc_multipatch\acq4\acq4\util\future.py", line 275, in _monitorErrors
    raise RuntimeError(formattedMsg) from exc
RuntimeError: Move to search position failed; requested from:
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\svc_multipatch\acq4\acq4\__main__.py", line 189, in <module>
    app.exec_()
  File "C:\Users\svc_multipatch\acq4\acq4\modules\MultiPatch\multipatch.py", line 458, in xkeysStateChanged
    for k,v in changes.items():
  File "C:\Users\svc_multipatch\acq4\acq4\modules\MultiPatch\multipatch.py", line 497, in xkeysAction
    self.updateXKeysBacklight()
  File "C:\Users\svc_multipatch\acq4\acq4\modules\MultiPatch\multipatch.py", line 273, in fineSearch
    self.moveSearch(distance)
  File "C:\Users\svc_multipatch\acq4\acq4\modules\MultiPatch\multipatch.py", line 278, in moveSearch
    for pip in pips:
  File "C:\Users\svc_multipatch\acq4\acq4\devices\Pipette\pipette.py", line 318, in goSearch
    return self.moveTo('search', speed=speed, distance=distance, **kwds)
  File "C:\Users\svc_multipatch\acq4\acq4\devices\Pipette\pipette.py", line 162, in moveTo
    return future
ERROR:PyTic:TIC_ERROR_INTENTIONALLY_DEENERGIZED
ERROR:PyTic:TIC_ERROR_INTENTIONALLY_DEENERGIZED
===== 2024.03.26 16:03:41 =====
Traceback (most recent call last):
  File "C:\Users\svc_multipatch\acq4\dependencies\pyqtgraph\pyqtgraph\graphicsItems\ImageItem.py", line 871, in paint
Windows fatal exception: access violation
Thread 0x00003f84 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\acq4\util\future.py", line 224 in sleep
  File "C:\Users\svc_multipatch\acq4\acq4\devices\Pipette\pipette.py", line 435 in stepwiseAdvance
  File "C:\Users\svc_multipatch\acq4\acq4\util\future.py", line 75 in _executeInThread
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 982 in run
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1045 in _bootstrap_inner
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1002 in _bootstrap
Thread 0x00004b44 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\acq4\util\future.py", line 224 in sleep
  File "C:\Users\svc_multipatch\acq4\acq4\devices\PatchPipette\states.py", line 1404 in run
  File "C:\Users\svc_multipatch\acq4\acq4\devices\PatchPipette\states.py", line 210 in _runJob
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 982 in run
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1045 in _bootstrap_inner
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1002 in _bootstrap
Thread 0x00004760 (most recent call first):
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\site-packages\PyDAQmx\DAQmxFunctions.py", line 57 in mafunction
  File "<string>", line 2 in function
  File "C:\Users\svc_multipatch\acq4\acq4\drivers\nidaq\nidaq.py", line 83 in call
  File "C:\Users\svc_multipatch\acq4\acq4\drivers\nidaq\nidaq.py", line 50 in <lambda>
  File "C:\Users\svc_multipatch\acq4\acq4\drivers\nidaq\nidaq.py", line 259 in <lambda>
  File "C:\Users\svc_multipatch\acq4\acq4\drivers\nidaq\nidaq.py", line 265 in start
  File "C:\Users\svc_multipatch\acq4\acq4\drivers\nidaq\SuperTask.py", line 256 in start
  File "C:\Users\svc_multipatch\acq4\acq4\devices\NiDAQ\nidaq.py", line 298 in start
  File "C:\Users\svc_multipatch\acq4\acq4\Manager.py", line 1066 in execute
  File "C:\Users\svc_multipatch\acq4\acq4\devices\PatchPipette\testpulse.py", line 147 in runOnce
  File "C:\Users\svc_multipatch\acq4\acq4\devices\PatchPipette\testpulse.py", line 87 in run
  File "C:\Users\svc_multipatch\acq4\acq4\util\Thread.py", line 36 in __run_wrapper
Current thread 0x000049d8 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\acq4\util\micromanager.py", line 37 in fn
  File "C:\Users\svc_multipatch\acq4\acq4\devices\MicroManagerCamera\mmcamera.py", line 133 in newFrames
  File "C:\Users\svc_multipatch\acq4\acq4\devices\Camera\Camera.py", line 862 in run
  File "C:\Users\svc_multipatch\acq4\acq4\util\Thread.py", line 36 in __run_wrapper
Thread 0x000048b8 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\acq4\util\future.py", line 214 in checkStop
  File "C:\Users\svc_multipatch\acq4\acq4\devices\Camera\Camera.py", line 995 in _monitorAcquisition
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 982 in run
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1045 in _bootstrap_inner
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1002 in _bootstrap
Thread 0x00003038 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\acq4\util\imaging\record_thread.py", line 142 in run
  File "C:\Users\svc_multipatch\acq4\acq4\util\Thread.py", line 36 in __run_wrapper
Thread 0x000038ac (most recent call first):
  File "C:\Users\svc_multipatch\acq4\acq4\drivers\MultiClamp\MultiClampTelegraph.py", line 157 in messageLoop
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 982 in run
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1045 in _bootstrap_inner
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1002 in _bootstrap
Thread 0x000040f4 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\acq4\devices\FilterWheel\filterwheel.py", line 456 in run
  File "C:\Users\svc_multipatch\acq4\acq4\util\Thread.py", line 36 in __run_wrapper
Thread 0x000041cc (most recent call first):
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 331 in wait
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\queue.py", line 180 in get
  File "C:\Users\svc_multipatch\acq4\dependencies\falconoptics\falconoptics\falcon.py", line 114 in _observer_loop
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 982 in run
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1045 in _bootstrap_inner
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1002 in _bootstrap
Thread 0x00004708 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\acq4\devices\Scientifica\scientifica.py", line 242 in run
  File "C:\Users\svc_multipatch\acq4\acq4\util\Thread.py", line 36 in __run_wrapper
Thread 0x00002e08 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\acq4\devices\Scientifica\scientifica.py", line 242 in run
  File "C:\Users\svc_multipatch\acq4\acq4\util\Thread.py", line 36 in __run_wrapper
Thread 0x00003728 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\dependencies\sensapex-py\sensapex\sensapex.py", line 1012 in run
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1045 in _bootstrap_inner
  File "C:\Users\svc_multipatch\AppData\Local\miniconda3\envs\acq4-torch\Lib\threading.py", line 1002 in _bootstrap
Thread 0x00003d34 (most recent call first):
  File "C:\Users\svc_multipatch\acq4\dependencies\pyqtgraph\pyqtgraph\Qt\__init__.py", line 314 in pyqt_qabort_override
  File "C:\Users\svc_multipatch\acq4\dependencies\pyqtgraph\pyqtgraph\exceptionHandling.py", line 109 in _excepthook
  File "C:\Users\svc_multipatch\acq4\dependencies\pyqtgraph\pyqtgraph\exceptionHandling.py", line 84 in sys_excepthook
  File "C:\Users\svc_multipatch\acq4\dependencies\pyqtgraph\pyqtgraph\widgets\GraphicsView.py", line 137 in paintEvent
  File "C:\Users\svc_multipatch\acq4\acq4\__main__.py", line 189 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main
```

**Comment by jessicatrnh** [comment]
ACQ4 closed out by itself.

**Comment by outofculture** [comment]
these continue to crop up, always with the same "Current thread"

**Comment by outofculture** [comment]
do just-popped images have the same address as the drawn images?

**Comment by campagnola** [comment]
Theory: we make a numpy array (and possibly Qt images) directly from micromanager-owned memory, and later on micromanager releases this memory despite np/Qt still holding a reference there. This would explain why in all crashed tracebacks we have two things consistently happening at the same time: micromanager popping an image from its stack, and Qt drawing a frame.

**Comment by outofculture** [comment]
The first dump here has a drawFrame, but the other 2 don't. They do have a GraphicsView.paintEvent, though. One common thread between them, though, is that all the Qt threads are in the middle of exceptions...

**Comment by outofculture** [comment]
Moreover, `self._imageItem.updateImage(data.copy())` is how the image data is getting into the ImageItem, so we're already copying the data before painting it.

**Comment by outofculture** [comment]
it could still be from use of the data other than painting it, though, so the general theory is still valid

**Comment by outofculture** [comment]
is it MP0 running out of memory? keep task manager open to track this.
