### ISSUE TITLE
Problems with NIDAQ and nicaui.dll

### ISSUE THREAD

**Issue by samuelgarcia** [acq4/acq4#70]
Hi Luke,
I face some problems running acq4 baceause of nidaq ddl.
This is the nicaui.dll.

From what I anderstand in the code. There is CLibrary class on top of ctype trying to parse header files and cache them. This is done at the first start.

It fails for me: I am not able to do this:
```
import acq4
from acq4.drivers.nidaq.nidaq import NIDAQ
n = NIDAQ
print(n.listDevices())
```

I also try to replace the "new" header in acq4 codes
**acq4\acq4\drivers\nidaq\NIDAQmx.h** is replace by the fresh installed one
**C:\Program Files (x86)\National Instruments\NI-DAQ\DAQmx ANSI C Dev\include\NIDAQmx.h"**

I have this erro in both cases:

Parsing C header files (no valid cache found). This could take several minutes...
Traceback (most recent call last):
  File "C:\Users\manip_intra\Documents\acq4\acq4\util\clibrary\CParser.py", line 1036, in processVariable
    (name, typ) = self.processType(t[0].type, d)
  File "C:\Users\manip_intra\Documents\acq4\acq4\util\clibrary\CParser.py", line 906, in processType
    (name, decl) = self.processDeclarator(decl)
  File "C:\Users\manip_intra\Documents\acq4\acq4\util\clibrary\CParser.py", line 876, in processDeclarator
    toks.append(tuple([self.processType(a['type'], a['decl']) + (a['val'][0],) for a in decl['args']]))
  File "C:\Users\manip_intra\AppData\Local\Continuum\anaconda3\envs\py27_acq4\lib\site-packages\pyparsing.py", line 390, in __getitem__
    return self.__toklist[i]
IndexError: list index out of range
Traceback (most recent call last):
  File "C:\Users\manip_intra\Documents\acq4\acq4\util\clibrary\CParser.py", line 1036, in processVariable
    (name, typ) = self.processType(t[0].type, d)
  File "C:\Users\manip_intra\Documents\acq4\acq4\util\clibrary\CParser.py", line 906, in processType
    (name, decl) = self.processDeclarator(decl)
  File "C:\Users\manip_intra\Documents\acq4\acq4\util\clibrary\CParser.py", line 876, in processDeclarator
    toks.append(tuple([self.processType(a['type'], a['decl']) + (a['val'][0],) for a in decl['args']]))
  File "C:\Users\manip_intra\AppData\Local\Continuum\anaconda3\envs\py27_acq4\lib\site-packages\pyparsing.py", line 390, in __getitem__
    return self.__toklist[i]
IndexError: list index out of range

**Comment by campagnola** [comment]
Can you verify for me that you have downgraded pyparsing to version 2.0.3?

**Comment by samuelgarcia** [comment]
Yep. Thank you.
pyparsing==2.0.3 fix the problem.
In will try the acq4 today and tell you more.
